In [ ]:
import numpy as np
from numpy import random
import sys

random.seed(173) #The last four digits of my number are 0173 but seems to exist a problem with 0.

#i
X = random.randint(random.randint(0, 10), size=(3,4))
Y = random.randint(random.randint(0, 10), size=(4,3))
print("X=",X)
print("Y=",Y)

X= [[4 3 0 3]
 [2 1 2 1]
 [3 3 1 3]]
Y= [[1 2 1]
 [3 1 1]
 [4 4 1]
 [0 0 3]]


In [ ]:
#ii
a = random.randint(random.randint(0, 10), size=(4))
b = random.randint(random.randint(0, 10), size=(4))
print("a=", a)
print("b=",b)

In [ ]:
#1.1
c = np.inner(a,b)
print("c=",c)

Αναλυτικός υπολογισμός του εσωτερικού γινομένου: 

a = (x1, y1, z1, v1)

b = (x2, y2, z2, v2)

<a,b> = x1 * x2 + y1 * y2 + z1 * z2 + v1 * v2 

Τα αποτελέσματα φαίνεται να επιβεβαιώνονται από τον παραπάνω κώδικα

In [ ]:
#1.2
d = np.dot(X,a)
print("d=", d)

d= [ 784 1138  912]


Έστω ένας πίνακας Χ = [ χ11, χ12, χ13, χ14
                        χ21, χ22, χ23, χ24
                        χ31, χ32, χ33, χ34 ]

και ένα διάνυσμα α = [ α1, α2, α3, α4]

Τότε το γινόμενο Χ*α είναι ίσο με:

= [α1 * χ11 + α1 * χ12 + α1 * χ13 + α1 * χ14, α2 * χ21 + α2 * χ22 + α2 * χ23 + α2 * χ24, α3 * χ31 + α3 * χ32 + α3 * χ33 + α3 * χ34]  

Το οποίο επιβεβαιώνεται από τον παραπάνω κώδικα.



In [ ]:
#1.3
e = np.dot(X, Y)
print("e=", e)

Έστω ένας πίνακας Χ = [ χ11, χ12, χ13, χ14
                        χ21, χ22, χ23, χ24
                        χ31, χ32, χ33, χ34 ]

Έστω ένας πίνακας Υ = [ y11, y12, y13
                        y21, y22, y23
                        y31, y32, y33
                        y41, y42, y43 ]

Τότε το γινόμενο X*Y ισόυται με έναν πίνακα διάστασης 3 * 3 που υπολογίζεται ως:

XY = [ 

  x11 * y11 + x12 * y21 + x13 * y31 + x14 * y41, x11 * y12 + x12 * y22 + x13 * y32 + x14 * y42, x11 * y13 + x12 * y23 + x13 * y33 + x14 * y43

  x21 * y11 + x22 * y21 + x23 * y31 + x24 * y41, x12 * y12 + x22 * y22 + x23 * y32 + x24 * y42, x12 * y13 + x22 * y23 + x23 * y33 + x24 * y43

  x31 * y11 + x32 * y21 + x33 * y31 + x34 * y41, x31 * y12 + x32 * y22 + x33 * y32 + x34 * y42, x31 * y13 + x32 * y23 + x33 * y33 + x34 * y43 ]

το οποίο αποδυκνείεται από τον παραπάνω κώδικα.

In [ ]:
#1.4
norm = np.linalg.norm(a)
print("norm=", norm)

norm= 20.639767440550294


Έστω ένα διάνυσμα: α = (α1, α2, α3, α4)

Η νόρμα του διανύσματος υπολογίζεται ως:

τετραγωνική_ρίζα(α1 * α1 + α2 * α2 + α3 * α3 + α4 * α4)

Το οποίο επιβεβαιώνεται από τον παραπάνω κώδικα.  

In [ ]:
#1.5
norm_fb = np.linalg.norm(X)
print("norm_fb=", norm_fb)

norm_fb= 51.85556864985669


Έστω ένας πίνακας Χ = [ χ11, χ12, χ13, χ14
                        χ21, χ22, χ23, χ24
                        χ31, χ32, χ33, χ34 ]

H Frobenius νόρμα του χ υπολογίζεται ως: ρίζα(Σ(i=1,4)Σ(j=1,3)(xij*xij))

το οποίο αποδεικνύεται από τον παραπάνω κώδικα.

#2.1

H παράγωγος της συνάρτησης: $ f(x) = x^TAx + b^Tx $ ισούται με το άθροισμα των παραγώγων τως συναρτήσεων: $ g(x) = x^TAx $ και $ h(x) = b^Tx $.

Για τις οποίες ισχύει:

$ h(x)  = x^Tb = 	\begin{bmatrix}x1 & .. & xn \end{bmatrix} \begin{bmatrix}b1\\ .. \\ bn \end{bmatrix} = b1*x1 + .. + bn*xn $ \\ \\

Συνεπώς για την παράγωγο ισχύει: \\ \\

$ \frac{\partial x^Tb}{\partial x} = 
\begin{bmatrix} \frac{\partial x^Tb}{\partial x1} \\ ..\\ \frac{\partial x^Tb}{\partial xn} \end{bmatrix} 
= \begin{bmatrix} \frac{\partial (b1x1+..+bnxn)}{\partial x1} \\ ..\\ \frac{\partial (b1x1+..+bnxn)}{\partial xn} \end{bmatrix}
= \begin{bmatrix}b1\\ .. \\ bn \end{bmatrix}
= b $

Για την g(x) έχουμε: 

$ g(x) = x^TAx = \begin{bmatrix}x1 & .. & xn \end{bmatrix}\begin{bmatrix}a11 & .. & a1n \\ .. & .. & .. \\ an1 & .. &ann \end{bmatrix}\begin{bmatrix}x1 \\ .. \\ xn \end{bmatrix} 
= \begin{bmatrix}(a11x1 + .. + an1xn) & .. & (a1nx1 + .. + annxn)\end{bmatrix}\begin{bmatrix}x1 \\s .. \\ xn \end{bmatrix} \\ 
= \begin{bmatrix}\sum_{i=1}^{n}ai1xi & .. & \sum_{i=1}^{n}ainxi \end{bmatrix}\begin{bmatrix}x1 \\ .. \\ xn \end{bmatrix} \\ 
= x1\sum_{i=1}^{n}ai1xi + .. + xn\sum_{i=1}^{n}ainxi \\ 
= \sum_{j=1}^{n} xj \sum_{i=1}^{n}aijxi \\ 
= \sum_{j=1}^{n}\sum_{i=1}^{n}aijxixj $ \\ 

Για την παράγωγο ισχύει: 

$ \frac{\partial x^TAx}{\partial x} = \begin{bmatrix}\frac{\partial x^TAx}{\partial x1} \\ .. \\ \frac{\partial x^TAx}{\partial xn} \end{bmatrix}$

Για την k-ιοστή σειρά του πίνακα ισχύει: 

$ \frac{\partial x^TAx}{\partial xk} =\\
= \frac{\partial}{\partial xk}\sum_{j=1}^{n}\sum_{i=1}^{n}aijxixj \\
=\frac{\partial}{\partial xk}(x1*\sum_{i=1}^{n}ai1xi
+ .. + xn*\sum_{i=1}^{n}ainxi) \\ 
= \sum_{j=1}^{n}akjxj + \sum_{i=1}^{n}aikxi \\ 
= (k^{th} row of A)x + (transpose of k^{th} column of A)x \\ 
= [(k^{th} row of A) + (transpose of k^{th} column of A)]x $ \\ 

Συνεπώς:

$ \frac{\partial x^TAx}{\partial x} = \\ 
= \begin{bmatrix}[(1^{st} row of A) + (transpose of 1{st} column of A)]x \\ .. \\ [(n^{th} row of A) + (transpose of n{th} column of A)]x \end{bmatrix}   \\
= (\begin{bmatrix} 1^{st} row of A \\ .. \\ n^{th} row of A \end{bmatrix} + \begin{bmatrix} transpose of 1^{st} column of A \\ .. \\ transpose of n^{th} column of A \end{bmatrix})x \\ 
= (A + A^T)x $ \\

Και επειδή ο πίνακας Α είναι συμμετρικός έχουμε: 

$ \frac{\partial x^TAx}{\partial x} = 2Ax $ 

Συνεπώς η παράγωγος: 

$ \frac{\partial (x^TAx + b^Tx)}{\partial x} = 2Ax + b $ 




#2.2
Έστω η συνάρτηση: $ l(w) = |A - XB| $

Για να υπολογιστεί το ελάχιστο της συνάρτησης ως προς Χ αρκεί να υπολογιστεί η πρώτη παράγωγος και να τεθεί ίση με 0.

$ minRSS = minl(w) = min|A - XB| \\
  l(w) = |A - XB| = (A - XB)^T(A - XB) $

Για την παράγωγο:

$ \frac{\partial l(X)}{\partial X} = -2X^TA - XB \\
  0 = -2X^T(A - XB) \\
  0 = X^T(A - XB) \\
  0 = X^TA - X^TXB \\ $

Άρα: 

$ X^TA = X^TXB $ \\



In [ ]:
#3.1.1
import numpy as np
import matplotlib.pyplot as plt

def gradient_descent1(gradient, gradient2, x1, x2, fx, learning_rate, T):
  plt.figure(figsize=(5,5))
  plt.ylabel("Function");plt.xlabel("i value")
  for i in range(0, T, 1):
    x1 = x1 - learning_rate*gradient(x1)
    x2 = x2 - learning_rate*gradient2(x2)
    res = fx(x1, x2)
    plt.scatter(i, res)
  plt.show()

def fx1(x1, x2):
  return (x1 - 2)**2 + (x2 - 3)**2

def gradient_x1_1(x1):
  return 2*(x1 - 2)

def gradient_x2_1(x2):
  return 2*(x2 - 3)

x1 = 0
x2 = 0

In [ ]:
gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, 0.5, 10)

Για learing_rate = 0.5 και 10 επαναλήψεις ο αλγόριθμος φαίνεται να δουλεύει και η συνάρτηση f1(x) συγκλινει σε μία ευθεία. 

In [ ]:
for a in np.arange(0.1, 0.9, 0.3):
  for T in range(10, 60, 20):
    print("a:", a, "T:", T)
    gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, a, T)

Με τις παραπάνω εντολές καλείται ο αλγόριθμος gradient descent για την f1(x) για διάφορες τιμές του learning_rate και διαφορετικό αριθμό επαναλήψεων. \\
Για learning_rate = 0.1 η συνάρτηση φαίνεται να συγκλινει για πάνω από 50 επαναλήψεις. 

Για learning_rate = 0.4 η συνάρτηση φαίνεται να συγκλινει για πάνω από 10 επαναλήψεις. 

Για learning_rate = 0.7 η συνάρτηση φαίνεται να συγκλινει για πάνω από 30 επαναλήψεις. 

Συνολικά ο αλγόριθμος φαίνεται να συμπεριφέρεται καλύτερα για learning_rate = 0.4 όπου αρκούν μόνο 10 επαναλήψεις για να συγκλινει.


In [ ]:
gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, 0.001, 30)
gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, 0.007, 30)
gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, 0.015, 30)

gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, 1.2, 30)
gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, 2.3, 30)
gradient_descent1(gradient_x1_1, gradient_x2_1, x1, x2, fx1, 5, 30)

Με τις παραπάνω εντολές δοκιμάζουμε τον αλγόριθμο με κάποιες μεγάλες και κάποιες μικρές τιμές του learning rate. Για μικρές τιμές βλέπουμε ότι η συνάρτηση έχει αρνητική κλίση και όσο μεγαλώνει εμφανίζεται μια μικρή κοιλότητα. Όταν το learning_rate γίνει μεγάλο η συνάρτηση πλέον είναι μια ευθεία γραμμή η οποία δεν μεταβάλλεται. 

In [ ]:
#3.1.2
import numpy as np
import matplotlib.pyplot as plt

def gradient_descent2(gradient, gradient2, x1, x2, fx, learning_rate, T):
  plt.figure(figsize=(5,5))
  plt.ylabel("Function");plt.xlabel("i value")
  for i in range(0, T, 1):
    x1 = x1 - learning_rate*gradient(x1, x2)
    x2 = x2 - learning_rate*gradient2(x1, x2)
    res = fx(x1, x2)
    plt.scatter(i, res)
    plt.plot(res, i)
  plt.show()

def fx2(x1, x2):
  return (1 - (x2 - 3))**2 + 20*((x1 + 3) - ((x2 - 3)**2))**2

def gradient_x1_2(x1, x2): 
  return 40*((x1 + 3) - (x2 - 3)**2)

def gradient_x2_2(x1, x2):
  return 2*(1 - (x2 - 3)) - 80*((x1 + 3) - (x2 - 3)**2)*(x2 - 3)

x1 = 0
x2 = 0

In [ ]:
gradient_descent2(gradient_x1_2, gradient_x2_2, x1, x2, fx2, 0.5, 10)

Για learing_rate = 0.5 και 10 επαναλήψεις ο αλγόριθμος φαίνεται να μην δουλεύει και να οδηγεί σε overflow για την συνάρτηση f2(x). 

In [ ]:
for a in np.arange(0.001, 0.009, 0.003):
  for T in range(10, 60, 20):
    print("a:", a, "T:", T)
    gradient_descent2(gradient_x1_2, gradient_x2_2, x1, x2, fx2, a, T)

Με τις παραπάνω εντολές καλείται ο αλγόριθμος gradient descent για την f2(x) για διάφορες τιμές του learning_rate και διαφορετικό αριθμό επαναλήψεων. \\
Για learning_rate = 0.001 η συνάρτηση φαίνεται να συγκλινει για πάνω από 30 επαναλήψεις. 

Για learning_rate = 0.004 η συνάρτηση φαίνεται να συγκλινει για πάνω από 50 επαναλήψεις ενώ τα σημεία είναι αρκετά άστατα. 

Για learning_rate >= 0.007 η συνάρτηση φαίνεται να οδηγεί σε overflow 

Συνολικά ο αλγόριθμος φαίνεται να συμπεριφέρεται καλύτερα για learning_rate = 0.001 όπου αρκούν μόνο 30 επαναλήψεις για να συγκλινει.


In [ ]:
gradient_descent2(gradient_x1_2, gradient_x2_2, x1, x2, fx2, 0.0001, 30)
gradient_descent2(gradient_x1_2, gradient_x2_2, x1, x2, fx2, 0.0009, 30)
gradient_descent2(gradient_x1_2, gradient_x2_2, x1, x2, fx2, 0.0015, 30)

gradient_descent2(gradient_x1_2, gradient_x2_2, x1, x2, fx2, 1, 30)
gradient_descent2(gradient_x1_2, gradient_x2_2, x1, x2, fx2, 2, 30)

Με τις παραπάνω εντολές δοκιμάζουμε τον αλγόριθμο με κάποιες μεγάλες και κάποιες μικρές τιμές του learning rate. Για μικρές τιμές η συνάρτηση έχει αρνητική κλίση και φαίνεται να συγκεντρώνεται γύρω από το 0 όπου για learning_rate = 0.0009 είναι μία ευθεία γραμμή. Για μεγάλες τιμές η συνάρτηση οδηγεί σε overflow και δεν έχουμε αποτέλεσμα.